// src/components/roomManagement/roomManagement.jsx
// ─── Real-time Room Management Page ───────────────────────────────────────────
// Features:
//   • Unique Room Code (RM-001) auto-generated by backend
//   • QR Code per room (for mobile check-in)
//   • GPS coordinates + "Use My Location" button
//   • Real-time occupancy via Socket.IO
//   • Live attendees list per room (poll every 10 s + socket push)
// ─────────────────────────────────────────────────────────────────────────────
import { useState, useEffect, useRef, useCallback } from "react";
import { io } from "socket.io-client";
import { QRCodeSVG } from "qrcode.react";
import MainMenu from "../mainMenu/mainMenu";

// ── Use relative URLs → Vite proxy forwards to backend (localhost:3001)
// ── On production/mobile set VITE_API_URL and VITE_WS_URL in .env
const API_BASE = import.meta.env.VITE_API_URL || "";
const WS_URL   = import.meta.env.VITE_WS_URL  || window.location.origin;

/* ─── helpers ────────────────────────────────────────────────────────────── */
const token = () => localStorage.getItem("token") || "";

async function apiFetch(path, opts = {}) {
  const res = await fetch(`${API_BASE}${path}`, {
    headers: {
      Authorization: `Bearer ${token()}`,
      "Content-Type": "application/json",
      ...opts.headers,
    },
    ...opts,
  });
  if (res.status === 401) throw new Error("AUTH_REQUIRED");
  if (!res.ok)            throw new Error(`HTTP ${res.status}`);
  return res.json();
}

// ── Demo rooms shown when backend is offline or user not logged in ────────────
const DEMO_ROOMS = [
  { id: 1, name: "Main Hall",     description: "Ground floor main hall",   capacity: 50, room_code: "RM-001", qr_token: "demo-1", latitude: 30.0444, longitude: 31.2357, current_occupancy: 12 },
  { id: 2, name: "Training Room", description: "Employee training area",   capacity: 30, room_code: "RM-002", qr_token: "demo-2", latitude: 30.0450, longitude: 31.2360, current_occupancy: 7  },
  { id: 3, name: "Meeting Room",  description: "Small executive meeting",  capacity: 20, room_code: "RM-003", qr_token: "demo-3", latitude: null,     longitude: null,     current_occupancy: 0  },
];

/* ─── sub-components ─────────────────────────────────────────────────────── */
function Badge({ label, color }) {
  const map = {
    green:  "bg-emerald-50 text-emerald-600 border-emerald-200",
    blue:   "bg-blue-50  text-blue-600  border-blue-200",
    gray:   "bg-gray-50  text-gray-500  border-gray-200",
    amber:  "bg-amber-50 text-amber-600 border-amber-200",
  };
  return (
    <span className={`text-xs font-medium border px-2.5 py-0.5 rounded-full ${map[color] || map.gray}`}>
      {label}
    </span>
  );
}

function LiveDot() {
  return (
    <span className="inline-flex items-center gap-1.5">
      <span className="relative flex h-2 w-2">
        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
        <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500" />
      </span>
      <span className="text-xs text-emerald-600 font-medium">Live</span>
    </span>
  );
}

function QRModal({ room, onClose }) {
  const qrValue = `ROOM:${room.qr_token}:${room.room_code}`;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onClick={onClose}>
      <div className="bg-white rounded-2xl p-8 shadow-2xl max-w-xs w-full mx-4 flex flex-col items-center gap-5"
           onClick={e => e.stopPropagation()}>
        <div className="text-center">
          <h3 className="text-base font-bold text-gray-900">{room.name}</h3>
          <p className="text-xs text-gray-400 mt-0.5">Scan to check in with mobile app</p>
        </div>

        <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
          <QRCodeSVG value={qrValue} size={200} level="H"
            imageSettings={{ src: "", height: 0, width: 0, excavate: true }} />
        </div>

        <div className="w-full space-y-2 text-center">
          <div className="bg-gray-900 text-white font-mono text-lg font-bold tracking-widest py-2 rounded-lg">
            {room.room_code}
          </div>
          <p className="text-xs text-gray-400">Room code for manual entry</p>
        </div>

        <button onClick={onClose}
          className="w-full border border-gray-200 text-sm text-gray-500 py-2 rounded-lg hover:bg-gray-50 transition-colors">
          Close
        </button>
      </div>
    </div>
  );
}

function AttendeesModal({ room, onClose }) {
  const [attendees, setAttendees] = useState([]);
  const [loading,   setLoading]   = useState(true);

  const fetchAttendees = useCallback(async () => {
    const data = await apiFetch(`/api/rooms/${room.id}/live`);
    if (data.success) setAttendees(data.attendees || []);
    setLoading(false);
  }, [room.id]);

  useEffect(() => {
    fetchAttendees();
    const t = setInterval(fetchAttendees, 10_000);
    return () => clearInterval(t);
  }, [fetchAttendees]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onClick={onClose}>
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md mx-4 overflow-hidden" onClick={e => e.stopPropagation()}>
        {/* header */}
        <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
          <div>
            <h3 className="text-sm font-bold text-gray-900">{room.name} — Live Attendees</h3>
            <div className="mt-0.5"><LiveDot /></div>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <i className="fa-solid fa-xmark text-lg" />
          </button>
        </div>

        {/* body */}
        <div className="max-h-80 overflow-y-auto">
          {loading ? (
            <div className="flex items-center justify-center py-10">
              <div className="w-6 h-6 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
            </div>
          ) : attendees.length === 0 ? (
            <div className="py-10 text-center text-sm text-gray-400">
              <i className="fa-solid fa-door-open text-2xl mb-2 block" />
              No one checked in yet today
            </div>
          ) : (
            <ul className="divide-y divide-gray-50">
              {attendees.map(a => (
                <li key={a.attendance_id} className="flex items-center gap-3 px-6 py-3">
                  <div className="w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center text-gray-400 shrink-0 text-xs font-bold uppercase">
                    {a.full_name_en?.[0] || "?"}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-gray-800 truncate">{a.full_name_en}</p>
                    <p className="text-xs text-gray-400">{a.employee_id || "—"}</p>
                  </div>
                  <div className="text-right shrink-0">
                    <Badge label={a.status} color={a.status === "present" ? "green" : "amber"} />
                    <p className="text-xs text-gray-300 mt-0.5">
                      {new Date(a.checkin_time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                    </p>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="px-6 py-3 border-t border-gray-100 text-xs text-gray-400 text-center">
          Auto-refreshes every 10 s · Updates pushed via WebSocket
        </div>
      </div>
    </div>
  );
}

/* ─── main component ─────────────────────────────────────────────────────── */
export default function RoomManagement() {
  const [rooms,        setRooms]        = useState([]);
  const [loading,      setLoading]      = useState(true);
  const [wsConnected,  setWsConnected]  = useState(false);
  const [showForm,     setShowForm]     = useState(false);
  const [saving,       setSaving]       = useState(false);
  const [saveError,    setSaveError]    = useState("");   // ← NEW
  const [qrRoom,       setQrRoom]       = useState(null);
  const [liveRoom,     setLiveRoom]     = useState(null);
  const [locating,     setLocating]     = useState(false);
  const [demoMode,     setDemoMode]     = useState(false);
  const [form, setForm] = useState({
    name: "", description: "", capacity: 30, lat: "", lng: "",
  });

  const socketRef = useRef(null);

  /* ── fetch rooms ── */
  const fetchRooms = useCallback(async () => {
    try {
      const data = await apiFetch("/api/rooms");
      if (data.success) {
        setRooms(data.rooms);
        setDemoMode(false);
      }
    } catch (err) {
      // Backend offline OR not logged in → show demo rooms so the UI is visible
      console.warn("Rooms API unavailable:", err.message);
      setRooms(DEMO_ROOMS);
      setDemoMode(true);
    } finally {
      setLoading(false);
    }
  }, []);

  /* ── socket.io real-time ── */
  useEffect(() => {
    fetchRooms();

    const socket = io(WS_URL, { transports: ["websocket", "polling"] });
    socketRef.current = socket;

    socket.on("connect",       () => setWsConnected(true));
    socket.on("disconnect",    () => setWsConnected(false));
    socket.on("rooms:update",  (payload) => {
      // payload = { rooms: [...], timestamp: "..." }
      if (payload?.rooms) setRooms(payload.rooms);
    });

    return () => socket.disconnect();
  }, [fetchRooms]);

  /* ── GPS ── */
  const handleUseLocation = () => {
    if (!navigator.geolocation) return;
    setLocating(true);
    navigator.geolocation.getCurrentPosition(
      pos => {
        setForm(f => ({ ...f, lat: pos.coords.latitude.toFixed(6), lng: pos.coords.longitude.toFixed(6) }));
        setLocating(false);
      },
      () => setLocating(false)
    );
  };

  /* ── save new room ── */
  const handleSave = async () => {
    if (!form.name.trim()) { setSaveError("Room name is required."); return; }
    if (!form.capacity || Number(form.capacity) < 1) { setSaveError("Capacity must be at least 1."); return; }
    setSaving(true);
    setSaveError("");
    try {
      const data = await apiFetch("/api/rooms", {
        method: "POST",
        body: JSON.stringify({
          name:        form.name.trim(),
          description: form.description.trim(),
          capacity:    Number(form.capacity),
          latitude:    form.lat ? parseFloat(form.lat) : null,
          longitude:   form.lng ? parseFloat(form.lng) : null,
        }),
      });
      if (data.success) {
        setRooms(prev => [...prev, { ...data.room, current_occupancy: 0 }]);
        setForm({ name: "", description: "", capacity: 30, lat: "", lng: "" });
        setShowForm(false);
        setSaveError("");
      } else {
        setSaveError(data.message || "Failed to save room.");
      }
    } catch (err) {
      setSaveError(
        err.message === "AUTH_REQUIRED"
          ? "You must be logged in as admin to add rooms."
          : err.message || "Server error — please try again."
      );
    } finally {
      setSaving(false);
    }
  };

  /* ── delete room ── */
  const handleDelete = async (id) => {
    if (!window.confirm("Deactivate this room?")) return;
    await apiFetch(`/api/rooms/${id}`, { method: "DELETE" });
    setRooms(prev => prev.filter(r => r.id !== id));
  };

  /* ── occupancy colour ── */
  const occupancyColor = (room) => {
    const pct = room.current_occupancy / room.capacity;
    if (pct >= 1)   return "text-red-500";
    if (pct >= 0.7) return "text-amber-500";
    return "text-emerald-500";
  };

  /* ── render ── */
  return (
    <>
      <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />

      <div className="flex h-screen bg-gray-50 font-sans overflow-hidden">
        <MainMenu />

        <div className="flex-1 px-8 py-8 overflow-y-auto">

          {/* ── Header ── */}
          <div className="flex items-start justify-between mb-6">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Room Management</h1>
              <p className="text-sm text-gray-400 mt-1">
                Each room has a unique code & QR for GPS-verified check-in
              </p>
            </div>
            <div className="flex items-center gap-3">
              {/* WS indicator */}
              <span className={`flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-full border
                ${wsConnected ? "text-emerald-600 bg-emerald-50 border-emerald-200"
                              : "text-gray-400 bg-gray-50 border-gray-200"}`}>
                <span className={`w-1.5 h-1.5 rounded-full ${wsConnected ? "bg-emerald-500 animate-pulse" : "bg-gray-300"}`} />
                {wsConnected ? "Real-time connected" : "Connecting…"}
              </span>

              {!showForm && (
                <button onClick={() => setShowForm(true)}
                  className="flex items-center gap-2 bg-gray-900 text-white text-sm font-medium px-4 py-2.5 rounded-lg hover:bg-gray-700 transition-colors">
                  <i className="fa-solid fa-plus" /> Add Room
                </button>
              )}
            </div>
          </div>

          {/* ── Demo-mode banner ── */}
          {demoMode && (
            <div className="mb-6 flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 text-sm">
              <i className="fa-solid fa-triangle-exclamation text-amber-500 mt-0.5 shrink-0" />
              <div>
                <p className="font-medium text-amber-800">Demo Mode — Backend not connected</p>
                <p className="text-amber-600 mt-0.5">
                  Showing sample rooms. To see real data:{" "}
                  <strong>1)</strong> Start the backend{" "}
                  (<code className="bg-amber-100 px-1 rounded text-xs">cd backend &amp;&amp; node server.js</code>){" "}
                  then <strong>2)</strong>{" "}
                  <a href="/login" className="underline font-medium">Sign in</a>.
                </p>
              </div>
            </div>
          )}

          {/* ── Add Room Form ── */}
          {showForm && (
            <div className="bg-white border border-gray-200 rounded-xl p-6 mb-6 shadow-sm">
              <h2 className="text-sm font-bold text-gray-900 mb-0.5">Add New Room</h2>
              <p className="text-xs text-gray-400 mb-5">
                A unique Room Code &amp; QR token will be auto-generated by the server
              </p>

              {/* Save error */}
              {saveError && (
                <div className="mb-4 flex items-center gap-2 px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
                  <i className="fa-solid fa-circle-exclamation shrink-0" />
                  {saveError}
                </div>
              )}

              <div className="grid grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">
                    Room Name <span className="text-red-500">*</span>
                  </label>
                  <input type="text" placeholder="e.g., Main Hall"
                    value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm text-gray-700 bg-gray-50 focus:outline-none focus:border-gray-400 focus:bg-white transition-colors" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">
                    Capacity <span className="text-red-500">*</span>
                  </label>
                  <input type="number" min="1"
                    value={form.capacity} onChange={e => setForm({ ...form, capacity: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm text-gray-700 bg-gray-50 focus:outline-none focus:border-gray-400 focus:bg-white transition-colors" />
                </div>
              </div>

              <div className="mb-4">
                <label className="text-xs font-medium text-gray-600 mb-1 block">Description</label>
                <input type="text" placeholder="Brief description"
                  value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}
                  className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm text-gray-700 bg-gray-50 focus:outline-none focus:border-gray-400 focus:bg-white transition-colors" />
              </div>

              <div className="grid grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">
                    Latitude <span className="text-red-500">*</span>
                  </label>
                  <input type="text" placeholder="e.g., 30.0444"
                    value={form.lat} onChange={e => setForm({ ...form, lat: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm text-gray-700 bg-gray-50 focus:outline-none focus:border-gray-400 focus:bg-white transition-colors" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">
                    Longitude <span className="text-red-500">*</span>
                  </label>
                  <input type="text" placeholder="e.g., 31.2357"
                    value={form.lng} onChange={e => setForm({ ...form, lng: e.target.value })}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm text-gray-700 bg-gray-50 focus:outline-none focus:border-gray-400 focus:bg-white transition-colors" />
                </div>
              </div>

              <button onClick={handleUseLocation} disabled={locating}
                className="w-full flex items-center justify-center gap-2 border border-gray-200 rounded-lg py-2.5 text-sm text-gray-500 hover:bg-gray-50 hover:text-gray-700 transition-colors mb-4 disabled:opacity-50">
                {locating
                  ? <><i className="fa-solid fa-spinner animate-spin" /> Detecting…</>
                  : <><i className="fa-solid fa-location-crosshairs" /> Use Current GPS Location</>}
              </button>

              <div className="grid grid-cols-2 gap-4">
                <button onClick={handleSave} disabled={saving}
                  className="flex items-center justify-center gap-2 bg-gray-900 text-white text-sm font-medium py-2.5 rounded-lg hover:bg-gray-700 transition-colors disabled:opacity-50">
                  {saving
                    ? <><i className="fa-solid fa-spinner animate-spin" /> Saving…</>
                    : <><i className="fa-solid fa-floppy-disk" /> Save Room</>}
                </button>
                <button onClick={() => setShowForm(false)}
                  className="flex items-center justify-center gap-2 border border-gray-200 text-gray-500 text-sm font-medium py-2.5 rounded-lg hover:bg-gray-50 transition-colors">
                  Cancel
                </button>
              </div>
            </div>
          )}

          {/* ── Loading ── */}
          {loading && (
            <div className="flex items-center justify-center py-20">
              <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
            </div>
          )}

          {/* ── Room Cards ── */}
          {!loading && (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
              {rooms.map(room => (
                <div key={room.id}
                  className="bg-white border border-gray-200 rounded-xl p-5 flex flex-col gap-4 shadow-sm hover:shadow-md transition-shadow">

                  {/* card header */}
                  <div className="flex items-start justify-between">
                    <div className="flex-1 min-w-0 pr-2">
                      <h2 className="text-sm font-semibold text-gray-900 truncate">{room.name}</h2>
                      <p className="text-xs text-gray-400 mt-0.5 truncate">{room.description || "No description"}</p>
                    </div>
                    <button onClick={() => handleDelete(room.id)}
                      className="text-gray-300 hover:text-red-500 transition-colors shrink-0 mt-0.5">
                      <i className="fa-solid fa-trash text-sm" />
                    </button>
                  </div>

                  {/* room code badge */}
                  <div className="flex items-center gap-2">
                    <span className="bg-gray-900 text-white font-mono text-xs font-bold px-3 py-1 rounded-lg tracking-wider">
                      {room.room_code}
                    </span>
                    <Badge label="Unique Code" color="gray" />
                  </div>

                  {/* occupancy */}
                  <div className="space-y-1.5">
                    <div className="flex items-center justify-between text-xs">
                      <span className="text-gray-400">Occupancy</span>
                      <span className={`font-semibold ${occupancyColor(room)}`}>
                        {room.current_occupancy ?? 0} / {room.capacity}
                      </span>
                    </div>
                    <div className="w-full h-1.5 bg-gray-100 rounded-full overflow-hidden">
                      <div className={`h-full rounded-full transition-all ${
                        (room.current_occupancy / room.capacity) >= 1 ? "bg-red-500"
                        : (room.current_occupancy / room.capacity) >= 0.7 ? "bg-amber-500"
                        : "bg-emerald-500"
                      }`}
                        style={{ width: `${Math.min(100, (room.current_occupancy / room.capacity) * 100)}%` }} />
                    </div>
                  </div>

                  {/* GPS */}
                  {(room.latitude && room.longitude) && (
                    <div className="flex items-center gap-1.5 text-xs text-gray-400">
                      <i className="fa-solid fa-location-dot text-gray-300" />
                      <span className="font-mono">
                        {Number(room.latitude).toFixed(4)}, {Number(room.longitude).toFixed(4)}
                      </span>
                    </div>
                  )}

                  {/* actions */}
                  <div className="grid grid-cols-3 gap-2 pt-1 border-t border-gray-100">
                    {/* QR */}
                    <button onClick={() => setQrRoom(room)}
                      className="flex flex-col items-center gap-1 py-2 rounded-lg text-gray-400 hover:bg-gray-50 hover:text-gray-700 transition-colors">
                      <i className="fa-solid fa-qrcode text-base" />
                      <span className="text-xs">QR Code</span>
                    </button>

                    {/* Live */}
                    <button onClick={() => setLiveRoom(room)}
                      className="flex flex-col items-center gap-1 py-2 rounded-lg text-gray-400 hover:bg-emerald-50 hover:text-emerald-600 transition-colors">
                      <i className="fa-solid fa-users text-base" />
                      <span className="text-xs">Live</span>
                    </button>

                    {/* Map */}
                    {(room.latitude && room.longitude) ? (
                      <a href={`https://www.google.com/maps?q=${room.latitude},${room.longitude}`}
                        target="_blank" rel="noreferrer"
                        className="flex flex-col items-center gap-1 py-2 rounded-lg text-gray-400 hover:bg-blue-50 hover:text-blue-600 transition-colors">
                        <i className="fa-solid fa-map-location-dot text-base" />
                        <span className="text-xs">Map</span>
                      </a>
                    ) : (
                      <div className="flex flex-col items-center gap-1 py-2 rounded-lg text-gray-200 cursor-not-allowed">
                        <i className="fa-solid fa-map-location-dot text-base" />
                        <span className="text-xs">Map</span>
                      </div>
                    )}
                  </div>
                </div>
              ))}

              {/* empty state */}
              {rooms.length === 0 && !showForm && (
                <div className="col-span-3 flex flex-col items-center justify-center py-20 text-center">
                  <i className="fa-solid fa-building text-4xl text-gray-200 mb-3" />
                  <p className="text-sm font-medium text-gray-400">No rooms yet</p>
                  <p className="text-xs text-gray-300 mt-1">Click "Add Room" to create your first room</p>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* ── Modals ── */}
      {qrRoom  && <QRModal       room={qrRoom}  onClose={() => setQrRoom(null)}  />}
      {liveRoom && <AttendeesModal room={liveRoom} onClose={() => setLiveRoom(null)} />}
    </>
  );
}